# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI - Master

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build sfui library
        run: npm run build --if-present
        env:
          CI: true
      - name: Git config
        if: success()
        run: |
          git config --local user.email "pedro.pdc.83@gmail.com"
          git config --local user.name "pedro.pdc.83"
      - name: Git status
        if: success()
        run: echo "Github user logged in"
      - name: Deploy example webpage to github pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy
        env:
          GH_TOKEN: MyCompany:${{ secrets.GITHUB_TOKEN }}
